### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by proesch2** [tomassurna/MyBlock#6]
allow functionality to search for posts by description

**Comment by proesch2** [comment]
Current update and plan to have search return a single postID query through the contract, further searches are done via frontend

**Comment by proesch2** [comment]
7a42508c5270b66ca166e4195ece2f041d45a3dd
75db38e5357e93c1383ff4f3f122eecbf81da4db

**Comment by proesch2** [comment]
Need to fix search to use substring contains

**Comment by tomassurna** [comment]
https://github.com/tomassurna/MyBlock/commit/0e9823631fccee9879de73f2b5c73435c92594e4
